name: pipeline

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  train_evaluate_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          kaggle datasets download -d uciml/electric-power-consumption-data-set
        
      - name: Unzip dataset
        run: unzip electric-power-consumption-data-set.zip
        
      # - name: Install data from firebase
      #   run: |
      #     python firebase_download.py

      - name: Run train_evaluate.py
        run: |
          python train_evaluate.py

      - name: Run firebase_upload.py
        env:
          FORECAST_KEY: ${{ secrets.FORECAST_KEY }}
        run: |
          python firebase_upload.py
