name: pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn scikit-learn keras tensorflow statsmodels kaggle firebase_admin

    - name: Run train_evaluate.py
      run: |
        python train_evaluate.py

    - name: Run firebase_upload.py
      run: |
        python firebase_upload.py

    - name: Archive result as artifact
      uses: actions/upload-artifact@v2
      with:
        name: predictions
        path: predictions.csv
